const nodemailer = require('nodemailer');

class EmailService {
  constructor() {
    this.transporter = null;
    this.initializeTransporter();
  }

  initializeTransporter() {
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASSWORD) {
      console.warn('Email service not configured. Set EMAIL_USER and EMAIL_PASSWORD in .env');
      return;
    }

    this.transporter = nodemailer.createTransport({
      service: process.env.EMAIL_SERVICE || 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASSWORD,
      },
    });
  }

  /**
   * Send report to agencies
   */
  async sendReportToAgencies(agencies, reportContent, referenceId) {
    if (!this.transporter) {
      throw new Error('Email service not configured');
    }

    const results = [];

    for (const agency of agencies) {
      try {
        const mailOptions = {
          from: process.env.EMAIL_USER,
          to: agency.email,
          subject: `Incident Report - ${referenceId}`,
          text: reportContent,
          html: this.formatReportHTML(reportContent, referenceId),
        };

        const info = await this.transporter.sendMail(mailOptions);
        results.push({
          agency: agency.name,
          success: true,
          messageId: info.messageId,
        });
      } catch (error) {
        console.error(`Failed to send email to ${agency.name}:`, error);
        results.push({
          agency: agency.name,
          success: false,
          error: error.message,
        });
      }
    }

    return results;
  }

  /**
   * Send confirmation email to user
   */
  async sendConfirmationToUser(userEmail, reportContent, referenceId, agencies) {
    if (!this.transporter) {
      throw new Error('Email service not configured');
    }

    try {
      const agencyList = agencies.map(a => a.name).join(', ');

      const mailOptions = {
        from: process.env.EMAIL_USER,
        to: userEmail,
        subject: `Report Confirmation - ${referenceId}`,
        text: `Your report has been submitted successfully.\n\nReference ID: ${referenceId}\nSent to: ${agencyList}\n\n${reportContent}`,
        html: this.formatConfirmationHTML(reportContent, referenceId, agencies),
      };

      const info = await this.transporter.sendMail(mailOptions);
      return {
        success: true,
        messageId: info.messageId,
      };
    } catch (error) {
      console.error('Failed to send confirmation email:', error);
      throw new Error('Failed to send confirmation email');
    }
  }

  /**
   * Format report as HTML
   */
  formatReportHTML(reportContent, referenceId) {
    return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #2563eb; color: white; padding: 20px; text-align: center; }
    .content { background: #f9fafb; padding: 20px; margin: 20px 0; }
    .footer { text-align: center; color: #6b7280; font-size: 12px; padding: 20px; }
    pre { white-space: pre-wrap; font-family: monospace; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Incident Report</h1>
      <p>Reference: ${referenceId}</p>
    </div>
    <div class="content">
      <pre>${reportContent}</pre>
    </div>
    <div class="footer">
      <p>This report was generated by ActionPoint Orbit's FixFinder AI</p>
      <p>Please review and take appropriate action</p>
    </div>
  </div>
</body>
</html>
    `;
  }

  /**
   * Format confirmation email as HTML
   */
  formatConfirmationHTML(reportContent, referenceId, agencies) {
    const agencyList = agencies.map(a => `<li>${a.name} (${a.fullName})</li>`).join('');

    return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #2563eb; color: white; padding: 20px; text-align: center; }
    .content { background: #f9fafb; padding: 20px; margin: 20px 0; }
    .footer { text-align: center; color: #6b7280; font-size: 12px; padding: 20px; }
    .success { background: #10b981; color: white; padding: 15px; margin: 20px 0; border-radius: 5px; }
    pre { white-space: pre-wrap; font-family: monospace; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Report Submitted Successfully</h1>
      <p>Reference: ${referenceId}</p>
    </div>
    <div class="success">
      <strong>✓ Your report has been sent to the following agencies:</strong>
      <ul>${agencyList}</ul>
    </div>
    <div class="content">
      <h3>Report Details:</h3>
      <pre>${reportContent}</pre>
    </div>
    <div class="footer">
      <p>You will receive updates as your case progresses</p>
      <p>Thank you for using ActionPoint Orbit's FixFinder</p>
    </div>
  </div>
</body>
</html>
    `;
  }
}

module.exports = new EmailService();
