const nodemailer = require('nodemailer');

/**
 * Escape user-supplied strings before embedding in HTML
 */
function escapeHtml(str) {
  if (typeof str !== 'string') return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;');
}

class EmailService {
  constructor() {
    this.transporter = null;
    this.initializeTransporter();
  }

  initializeTransporter() {
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASSWORD) {
      console.warn('Email service not configured. Set EMAIL_USER and EMAIL_PASSWORD in .env');
      return;
    }

    this.transporter = nodemailer.createTransport({
      service: process.env.EMAIL_SERVICE || 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASSWORD,
      },
    });
  }

  /**
   * Send report to agencies
   */
  async sendReportToAgencies(agencies, reportContent, referenceId) {
    if (!this.transporter) {
      throw new Error('Email service not configured');
    }

    const results = [];

    for (const agency of agencies) {
      try {
        const mailOptions = {
          from: process.env.EMAIL_USER,
          to: agency.email,
          subject: `Incident Report - ${escapeHtml(referenceId)}`,
          // Plain text version — no HTML injection risk
          text: `Incident Report\nReference: ${referenceId}\n\n${reportContent}`,
          html: this.formatReportHTML(reportContent, referenceId),
        };

        const info = await this.transporter.sendMail(mailOptions);
        results.push({
          agency: agency.name,
          success: true,
          messageId: info.messageId,
        });
      } catch (error) {
        console.error(`Failed to send email to ${agency.name}:`, error.message);
        results.push({
          agency: agency.name,
          success: false,
          error: error.message,
        });
      }
    }

    return results;
  }

  /**
   * Send confirmation email to user
   */
  async sendConfirmationToUser(userEmail, reportContent, referenceId, agencies) {
    if (!this.transporter) {
      throw new Error('Email service not configured');
    }

    try {
      const agencyList = agencies.map((a) => escapeHtml(a.name)).join(', ');

      const mailOptions = {
        from: process.env.EMAIL_USER,
        to: userEmail,
        subject: `Report Confirmation - ${escapeHtml(referenceId)}`,
        text: `Your report has been submitted successfully.\n\nReference ID: ${referenceId}\nSent to: ${agencies.map((a) => a.name).join(', ')}\n\n${reportContent}`,
        html: this.formatConfirmationHTML(reportContent, referenceId, agencies),
      };

      const info = await this.transporter.sendMail(mailOptions);
      return { success: true, messageId: info.messageId };
    } catch (error) {
      console.error('Failed to send confirmation email:', error.message);
      throw new Error('Failed to send confirmation email');
    }
  }

  /**
   * Format report as HTML — all user content is escaped
   */
  formatReportHTML(reportContent, referenceId) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'">
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #2563eb; color: white; padding: 20px; text-align: center; }
    .content { background: #f9fafb; padding: 20px; margin: 20px 0; }
    .footer { text-align: center; color: #6b7280; font-size: 12px; padding: 20px; }
    pre { white-space: pre-wrap; font-family: monospace; word-break: break-word; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Incident Report</h1>
      <p>Reference: ${escapeHtml(referenceId)}</p>
    </div>
    <div class="content">
      <pre>${escapeHtml(reportContent)}</pre>
    </div>
    <div class="footer">
      <p>This report was generated by Mori Smart Action Engine</p>
      <p>Please review and take appropriate action</p>
    </div>
  </div>
</body>
</html>`;
  }

  /**
   * Format confirmation email as HTML — all user content is escaped
   */
  formatConfirmationHTML(reportContent, referenceId, agencies) {
    const agencyListHtml = agencies
      .map((a) => `<li>${escapeHtml(a.name)} (${escapeHtml(a.fullName)})</li>`)
      .join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'">
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #2563eb; color: white; padding: 20px; text-align: center; }
    .content { background: #f9fafb; padding: 20px; margin: 20px 0; }
    .footer { text-align: center; color: #6b7280; font-size: 12px; padding: 20px; }
    .success { background: #10b981; color: white; padding: 15px; margin: 20px 0; border-radius: 5px; }
    pre { white-space: pre-wrap; font-family: monospace; word-break: break-word; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Report Submitted Successfully</h1>
      <p>Reference: ${escapeHtml(referenceId)}</p>
    </div>
    <div class="success">
      <strong>&#10003; Your report has been sent to the following agencies:</strong>
      <ul>${agencyListHtml}</ul>
    </div>
    <div class="content">
      <h3>Report Details:</h3>
      <pre>${escapeHtml(reportContent)}</pre>
    </div>
    <div class="footer">
      <p>You will receive updates as your case progresses</p>
      <p>Thank you for using Mori Smart Action Engine</p>
    </div>
  </div>
</body>
</html>`;
  }
}

module.exports = new EmailService();
